import { IChat } from "../features/telegram/telegramSlice";

export const DUMMY_CHATS_LIST: IChat[] = [
  {
    id: 5122222407,
    first_name: "Al",
    last_name: "Zel",
    username: "sasha_zelenkov",
    lastReaction: "Dog",
    date_of_last_display: 0,
  },
  {
    id: 5122222409,
    first_name: "Nikolay",
    last_name: "Zelllenkov",
    username: "kolya_zelenkov",
    lastReaction: "Cat",
    date_of_last_display: 3,
  },
  {
    id: 5122222443,
    first_name: "Al",
    last_name: "Zel",
    username: "sasha_zelenkov",
    lastReaction: "Dog",
    date_of_last_display: 0,
  },
  {
    id: 5122222400,
    first_name: "Nikolay",
    last_name: "Zelllenkov",
    username: "kolya_zelenkov",
    lastReaction: "Cat",
    date_of_last_display: 3,
  },
  {
    id: 5122222497,
    first_name: "Al",
    last_name: "Zel",
    username: "sasha_zelenkov",
    lastReaction: "Dog",
    date_of_last_display: 0,
  },
  {
    id: 5122221555,
    first_name: "Nikolay",
    last_name: "Zelllenkov",
    username: "kolya_zelenkov",
    lastReaction: "Cat",
    date_of_last_display: 3,
  },
  {
    id: 5122222440,
    first_name: "Nikolay",
    last_name: "Zelllenkov",
    username: "kolya_zelenkov",
    lastReaction: "Cat",
    date_of_last_display: 3,
  },
  {
    id: 5122222456,
    first_name: "Nikolay",
    last_name: "Zelllenkov",
    username: "kolya_zelenkov",
    lastReaction: "Cat",
    date_of_last_display: 3,
  },
  {
    id: 512222246,
    first_name: "Nikolay",
    last_name: "Zelllenkov",
    username: "kolya_zelenkov",
    lastReaction: "Cat",
    date_of_last_display: 3,
  },
  {
    id: 5122222445,
    first_name: "Nikolay",
    last_name: "Zelllenkov",
    username: "kolya_zelenkov",
    lastReaction: "Cat",
    date_of_last_display: 3,
  },
  {
    id: 5122222498,
    first_name: "Nikolay",
    last_name: "Zelllenkov",
    username: "kolya_zelenkov",
    lastReaction: "Cat",
    date_of_last_display: 3,
  },
];

export const DUMMY_CHATS_LIST2: IChat[] = [
  {
    id: 5122222407,
    first_name: "Al",
    last_name: "Zel",
    username: "sasha_zelenkov",
    lastReaction: "Dog",
    date_of_last_display: 0,
  },
  {
    id: 5122222409,
    first_name: "Nikolay",
    last_name: "Zelllenkov",
    username: "kolya_zelenkov",
    lastReaction: "Cat",
    date_of_last_display: 3,
  },
];

export const DUMMY_CHATS_LIST3: IChat[] = [
  {
    id: 5122222407,
    first_name: "Al",
    last_name: "Zel",
    username: "sasha_zelenkov",
    lastReaction: "Dog",
    date_of_last_display: 0,
  },
  {
    id: 5122222409,
    first_name: "Nikolay",
    last_name: "Zelllenkov",
    username: "kolya_zelenkov",
    lastReaction: "Cat",
    date_of_last_display: 3,
  },
  {
    id: 5122222443,
    first_name: "Al",
    last_name: "Zel",
    username: "sasha_zelenkov",
    lastReaction: "Dog",
    date_of_last_display: 0,
  },
];

export const DUMMY_CHATS_LIST6: IChat[] = [
  {
    id: 5122222407,
    first_name: "Al",
    last_name: "Zel",
    username: "sasha_zelenkov",
    lastReaction: "Dog",
    date_of_last_display: 0,
  },
  {
    id: 5122222409,
    first_name: "Nikolay",
    last_name: "Zelllenkov",
    username: "kolya_zelenkov",
    lastReaction: "Cat",
    date_of_last_display: 3,
  },
  {
    id: 5122222443,
    first_name: "Al",
    last_name: "Zel",
    username: "sasha_zelenkov",
    lastReaction: "Dog",
    date_of_last_display: 0,
  },
  {
    id: 5122222400,
    first_name: "Nikolay",
    last_name: "Zelllenkov",
    username: "kolya_zelenkov",
    lastReaction: "Cat",
    date_of_last_display: 3,
  },
  {
    id: 5122222497,
    first_name: "Al",
    last_name: "Zel",
    username: "sasha_zelenkov",
    lastReaction: "Dog",
    date_of_last_display: 0,
  },
  {
    id: 5122221555,
    first_name: "Nikolay",
    last_name: "Zelllenkov",
    username: "kolya_zelenkov",
    lastReaction: "Cat",
    date_of_last_display: 3,
  },
];

export const DUMMY_CHATS_LIST7: IChat[] = [
  {
    id: 5122222407,
    first_name: "Al",
    last_name: "Zel",
    username: "sasha_zelenkov",
    lastReaction: "Dog",
    date_of_last_display: 0,
  },
  {
    id: 5122222409,
    first_name: "Nikolay",
    last_name: "Zelllenkov",
    username: "kolya_zelenkov",
    lastReaction: "Cat",
    date_of_last_display: 3,
  },
  {
    id: 5122222443,
    first_name: "Al",
    last_name: "Zel",
    username: "sasha_zelenkov",
    lastReaction: "Dog",
    date_of_last_display: 0,
  },
  {
    id: 5122222400,
    first_name: "Nikolay",
    last_name: "Zelllenkov",
    username: "kolya_zelenkov",
    lastReaction: "Cat",
    date_of_last_display: 3,
  },
  {
    id: 5122222497,
    first_name: "Al",
    last_name: "Zel",
    username: "sasha_zelenkov",
    lastReaction: "Dog",
    date_of_last_display: 0,
  },
  {
    id: 5122221555,
    first_name: "Nikolay",
    last_name: "Zelllenkov",
    username: "kolya_zelenkov",
    lastReaction: "Cat",
    date_of_last_display: 3,
  },
  {
    id: 5122222440,
    first_name: "Nikolay",
    last_name: "Zelllenkov",
    username: "kolya_zelenkov",
    lastReaction: "Cat",
    date_of_last_display: 3,
  },
  {
    id: 5122222456,
    first_name: "Nikolay",
    last_name: "Zelllenkov",
    username: "kolya_zelenkov",
    lastReaction: "Cat",
    date_of_last_display: 3,
  },
];
